// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://codowtnijiaigehgtvxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvZG93dG5pamlhaWdlaGd0dnh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTc2NzYsImV4cCI6MjA3MTU3MzY3Nn0.bdL3_keDM7kJ2fIqnbtnbq5FEc9dA_zoR5HQnJt5INc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});